apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qjff
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-qjff@sha256:c6a1cb9f66a39fb96f108e377a3898a2c30e18e0d683ce375d544404cb68d13c
        name: my-nodejs
        resources: {}
status: {}
